version: '3'

services:
  recommnedsongs-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - sqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  recommnedsongs-backend:
    command: dotnet watch run
    image: recommnedsongs-backend
    build: 
      context: recommendSongsService.API
    depends_on:
      - recommnedsongs-db
    restart: always
    volumes:
      - ./recommendSongsService.API:/app
    ports:
      - "5000:5000"
      - "5001:5001"
volumes:
  sqldata: