version: '3'

services:
  recommendsongs-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: RecommendSongsDB
      POSTGRES_PASSWORD: example
    volumes:
      - sqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  recommendsongs-backend:
    command: bash -c "dotnet ef database update && dotnet watch run"
    image: recommendsongs-backend
    build: 
      context: recommendSongsService.API
    depends_on:
      - recommendsongs-db
    restart: always
    environment:
      DOTNETCORE_ENVIRONMENT: Development
    volumes:
      - ./recommendSongsService.API:/app
    ports:
      - "5000:5000"
      - "5001:5001"
volumes:
  sqldata: